[server]
host = "0.0.0.0"
port = "8080"

[log]
max_level = "info"

[[reconciler.matchers]]
[reconciler.matchers.taint]
effect = "NoExecute"
key = "pressure"
value = "memory"

[[reconciler.matchers.conditions]]
type = "foo(bar"
status = "Kaput|Ruined"

[[reconciler.matchers.conditions]]
type = "marco(polo"
status = "severed"
