[server]
host = "0.0.0.0"
port = "8080"

[log]
max_level = "info"

[[reconciler.matchers]]
[reconciler.matchers.taint]
effect = "NoExecute"
key = "taste"
value = "bland"

[[reconciler.matchers.conditions]]
type = "OutOfChocolate"
status = "(?i)true"

