apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app: tainter
namespace: tainter
resources:
  - namespace.yaml
  - deployment.yaml
  - rbac.yaml
configMapGenerator:
  - name: tainter-config
    files:
      - config.toml
