apiVersion: v1
kind: ServiceAccount
metadata:
  name: tainter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tainter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - update
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tainter
subjects:
  - kind: ServiceAccount
    name: tainter
    namespace: tainter
roleRef:
  kind: ClusterRole
  name: tainter
  apiGroup: rbac.authorization.k8s.io
