on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'The built image will be tagged with this version'
      push:
        required: false
        type: boolean
        default: false
        description: 'Whether to push the built image'

jobs:
  build:
    name: Image
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Construct image tag
        id: tag
        run: echo "tag=${{ secrets.DOCKERHUB_USERNAME }}/tainter:${{ inputs.version }}" >> "$GITHUB_OUTPUT"
      - name: Build image
        run: IMAGE_TAG=${{ steps.tag.outputs.tag }} make image
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        if: inputs.push == true
        run: |
          docker image push ${{ steps.tag.outputs.tag }}
