name: Main

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [test, lint]
    with:
      version: '${{ github.sha }}'
      push: true
