name: Pull Requests

on:
  pull_request:

jobs:
#  test:
#    name: Test
#    uses: ./.github/workflows/test.yml
#  lint:
#    name: Lint
#    uses: ./.github/workflows/lint.yml
#  end-to-end:
#    name: End-to-end
#    uses: ./.github/workflows/test-end-to-end.yml
  kubeconform:
    name: Kubeconform
    uses: ./.github/workflows/kubeconform.yml
