name: Pull Requests

on:
  pull_request:

jobs:
#  test:
#    name: Test
#    uses: ./.github/workflows/test.yml
#  lint:
#    name: Lint
#    uses: ./.github/workflows/lint.yml
  end-to-end:
    name: Lint
    uses: ./.github/workflows/test-end-to-end.yml
