on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'The built image will be tagged with this version'
      platforms:
        required: true
        type: string
        default: 'linux/amd64'
        description: 'Platform(s) for which to build the image. Example: "linux/amd64,linux/arm64".'

jobs:
  publish:
    name: Image
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Construct image tag
        id: tag
        run: echo "tag=${{ secrets.DOCKERHUB_USERNAME }}/tainter:${{ inputs.version }}" >> "$GITHUB_OUTPUT"
      - name: Log in
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker buildx build --push --tag ${{ steps.tag.outputs.tag }} --platform ${{ inputs.platforms }} .
