name: Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    needs: [test, lint]
    with:
      # https://github.com/orgs/community/discussions/26686#discussioncomment-3396593.
      version: '${{ github.ref_name }}'
      platforms: 'linux/amd64,linux/arm64'
