name: Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  end-to-end:
    name: End-to-end
    uses: ./.github/workflows/test-end-to-end.yml
  kubeconform:
    name: Kubeconform
    uses: ./.github/workflows/kubeconform.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [test, lint, end-to-end, kubeconform]
    with:
      # https://github.com/orgs/community/discussions/26686#discussioncomment-3396593.
      version: '${{ github.ref_name }}'
      push: true
      platform: 'linux/amd64,linux/arm64'
