on:
  workflow_call:

env:
  RUST_VERSION: '1.82.0'

jobs:
  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      # https://github.com/actions-rs/toolchain/issues/54#issuecomment-1452937296.
#      - id: cache-rustup
#        name: Cache Rust toolchain
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.rustup
#            ~/.cargo
#          key: toolchain-${{ env.RUST_VERSION }}
#      - if: ${{ steps.cache-rustup.outputs.cache-hit != 'true' }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.82.0'
      - name: Cache Rust toolchain
        uses: Swatinem/rust-cache@v2.7.5
      - name: Test
        run: make test
