on:
  workflow_call:

jobs:
  unit:
    name: Unit
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.82.0'
      - name: Cache Rust toolchain
        uses: Swatinem/rust-cache@v2.7.5
      - name: Test
        run: make test
  end-to-end:
    name: End-to-end
    strategy:
      matrix:
        kubernetes-version: [ 'v1.29.7', 'v1.30.6', 'v1.31.0' ]
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Minikube
        uses: medyagh/setup-minikube@v0.0.18
        with:
          start: false
      - name: Setup for test
        run: END_TO_END_TEST_KUBERNETES_VERSION=${{ matrix.kubernetes-version }} make setup
      - name: Run end-to-end tests
        run: make test-end-to-end
